"""
S1Gate MCP Server — Universal stdio MCP interface.

Exposes three tools to any MCP-compatible agent harness (IBM Bob IDE,
Claude Code, Agrav, Kiro, Codex, DeepSeek):

  s1gate_triage_diff          Evaluate a unified diff.
  s1gate_inspect_file         Evaluate staged changes in a specific file.
  s1gate_verify_remediation   Actor-Critic: verify an agent's fix patch.

(Also registers `kevgate_*` aliases for backwards compatibility).

Run as:
  python -m kevgate.mcp_server

Or register in Bob IDE mcp.json:
  { "command": "python", "args": ["-m", "kevgate.mcp_server"] }
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path
from typing import Any

import mcp.server.stdio
import mcp.types as types
from mcp.server import Server
from mcp.server.models import InitializationOptions

from kevgate.config import S1GateConfig
from kevgate.diff_parser import (
    chunks_to_condensed_diff,
    extract_file_diff,
    filter_triageable,
    parse_unified_diff,
)
from kevgate.entropy_scanner import scan_diff
from kevgate.exceptions import DecisionParseError, LMStudioUnavailableError
from kevgate.gemini_client import GeminiClient
from kevgate.lmstudio_client import LMStudioClient
from kevgate.policy_engine import evaluate, format_gate_result, generate_bob_task

# ---------------------------------------------------------------------------
# Server setup
# ---------------------------------------------------------------------------

_config = S1GateConfig()
server = Server(_config.mcp_server_name)


# ---------------------------------------------------------------------------
# Tools Definition
# ---------------------------------------------------------------------------

def _build_tools_list() -> list[types.Tool]:
    tools = []
    for prefix in ["s1gate", "kevgate"]:
        tools.extend([
            types.Tool(
                name=f"{prefix}_triage_diff",
                description=(
                    "Evaluate a unified git diff through S1Gate's System-1 decision engine. "
                    "Returns a risk classification, score (0-100), and remediation hints."
                ),
                inputSchema={
                    "type": "object",
                    "properties": {
                        "diff": {
                            "type": "string",
                            "description": "Unified git diff text (output of `git diff --cached` or similar).",
                        },
                        "context": {
                            "type": "string",
                            "description": "Optional commit message or PR description for additional context.",
                        },
                    },
                    "required": ["diff"],
                },
            ),
            types.Tool(
                name=f"{prefix}_inspect_file",
                description=(
                    "Evaluate staged or uncommitted changes in a specific file. "
                    "Automatically extracts the diff from the current git repository."
                ),
                inputSchema={
                    "type": "object",
                    "properties": {
                        "file_path": {
                            "type": "string",
                            "description": "Path to the file relative to the repository root.",
                        },
                    },
                    "required": ["file_path"],
                },
            ),
            types.Tool(
                name=f"{prefix}_verify_remediation",
                description=(
                    "Actor-Critic verification loop: checks whether an agent's remediation patch "
                    "resolves the risk identified in the original blocked diff. "
                    "Returns verified status, score delta, and a verdict message."
                ),
                inputSchema={
                    "type": "object",
                    "properties": {
                        "original_diff": {
                            "type": "string",
                            "description": "The diff that was blocked by S1Gate.",
                        },
                        "remediation_patch": {
                            "type": "string",
                            "description": "The patch generated by the agent to fix the issue.",
                        },
                        "previous_score": {
                            "type": "integer",
                            "description": "Risk score of the original diff (optional, for context).",
                        },
                    },
                    "required": ["original_diff", "remediation_patch"],
                },
            ),
        ])
    return tools


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return _build_tools_list()


# ---------------------------------------------------------------------------
# Tool call handler
# ---------------------------------------------------------------------------

@server.call_tool()
async def call_tool(
    name: str,
    arguments: dict[str, Any],
) -> list[types.TextContent]:
    config = S1GateConfig()

    if name in ("s1gate_triage_diff", "kevgate_triage_diff"):
        return await _handle_triage_diff(arguments, config)
    elif name in ("s1gate_inspect_file", "kevgate_inspect_file"):
        return await _handle_inspect_file(arguments, config)
    elif name in ("s1gate_verify_remediation", "kevgate_verify_remediation"):
        return await _handle_verify_remediation(arguments, config)
    else:
        return [types.TextContent(type="text", text=f"Unknown tool: {name}")]


async def _handle_triage_diff(
    arguments: dict[str, Any],
    config: S1GateConfig,
) -> list[types.TextContent]:
    diff = arguments["diff"]
    context = arguments.get("context")

    # Pre-filter
    secret_findings = scan_diff(diff, entropy_threshold=config.entropy_threshold)
    chunks = parse_unified_diff(diff)
    triageable = filter_triageable(chunks)
    condensed = chunks_to_condensed_diff(triageable) if triageable else diff[:4000]

    try:
        if config.backend == "gemini":
            client = GeminiClient(config)
            payload = await client.triage_diff_async(condensed, context=context)
        else:
            async with LMStudioClient(config) as client:
                payload = await client.triage_diff(condensed, context=context)
    except LMStudioUnavailableError as exc:
        return [types.TextContent(type="text", text=f"ERROR: {exc}")]
    except DecisionParseError as exc:
        return [types.TextContent(type="text", text=f"ERROR: Failed to parse model response: {exc}")]

    decision = evaluate(payload, config, secret_findings_count=len(secret_findings))

    # On BLOCK: generate Bob task
    if decision.value == "BLOCK":
        try:
            generate_bob_task(payload)
        except Exception:
            pass  # Non-fatal; Bob task generation is best-effort

    result = {
        "decision": decision.value,
        "payload": payload.model_dump(),
        "secret_findings_count": len(secret_findings),
        "summary": format_gate_result(decision, payload, len(secret_findings), use_color=False),
    }
    return [types.TextContent(type="text", text=json.dumps(result, indent=2))]


async def _handle_inspect_file(
    arguments: dict[str, Any],
    config: S1GateConfig,
) -> list[types.TextContent]:
    file_path = arguments["file_path"]

    try:
        diff = extract_file_diff(file_path)
    except Exception as exc:
        return [types.TextContent(type="text", text=f"ERROR: Could not extract diff for {file_path}: {exc}")]

    if not diff.strip():
        return [types.TextContent(
            type="text",
            text=json.dumps({"decision": "PASS", "message": f"No changes detected in {file_path}."})
        )]

    return await _handle_triage_diff({"diff": diff, "context": f"File inspection: {file_path}"}, config)


async def _handle_verify_remediation(
    arguments: dict[str, Any],
    config: S1GateConfig,
) -> list[types.TextContent]:
    original_diff = arguments["original_diff"]
    remediation_patch = arguments["remediation_patch"]
    previous_score = arguments.get("previous_score") or 70

    try:
        if config.backend == "gemini":
            client = GeminiClient(config)
            result = await client.verify_remediation_async(
                original_diff=original_diff,
                remediation_patch=remediation_patch,
                previous_score=previous_score,
            )
        else:
            async with LMStudioClient(config) as client:
                result = await client.verify_remediation(
                    original_diff=original_diff,
                    remediation_patch=remediation_patch,
                    previous_score=previous_score,
                )
    except LMStudioUnavailableError as exc:
        return [types.TextContent(type="text", text=f"ERROR: {exc}")]
    except DecisionParseError as exc:
        return [types.TextContent(type="text", text=f"ERROR: {exc}")]

    return [types.TextContent(type="text", text=result.model_dump_json(indent=2))]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def main() -> None:
    async with mcp.server.stdio.stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name=_config.mcp_server_name,
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=None,
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
